import { IMAGES } from "shared/config/images";

export const MOCK_PRODUCTS = [
  {
    id: 1,
    title: "Black Sweatshirt",
    brand: "Jhanvi's Brand",
    price: 123,
    image: IMAGES.prod1,
    category: "men",
    type: "hoodies",
    rating: 4.5,
    colors: ["black", "gray"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 2,
    title: "Line Pattern Hoodie",
    brand: "AS's Brand",
    price: 37,
    image: IMAGES.prod2,
    category: "men",
    type: "hoodies",
    rating: 4,
    colors: ["black"],
    sizes: ["M", "L"],
  },
  {
    id: 3,
    title: "Black Shorts",
    brand: "MM's Brand",
    price: 37,
    image: IMAGES.prod3,
    category: "women",
    type: "shorts",
    rating: 5,
    colors: ["black"],
    sizes: ["S", "M"],
  },
  {
    id: 4,
    title: "Lavender Hoodie",
    brand: "Nike's Brand",
    price: 119,
    image: IMAGES.prod4,
    category: "women",
    type: "hoodies",
    rating: 4.5,
    colors: ["purple"],
    sizes: ["S", "M", "L"],
  },
  {
    id: 5,
    title: "White T-Shirt",
    brand: "Priya's Brand",
    price: 15,
    image: IMAGES.prod5,
    category: "women",
    type: "tshirts",
    rating: 4,
    colors: ["white"],
    sizes: ["XS", "S", "M"],
  },
  {
    id: 6,
    title: "Dark Green Sweatshirt",
    brand: "Robato's Brand",
    price: 127,
    image: IMAGES.prod6,
    category: "men",
    type: "hoodies",
    rating: 5,
    colors: ["green"],
    sizes: ["M", "L", "XL"],
  },
  {
    id: 7,
    title: "Lavender Sweatshirt",
    brand: "Jhanvi's Brand",
    price: 133,
    image: IMAGES.prod7,
    category: "women",
    type: "hoodies",
    rating: 4,
    colors: ["purple"],
    sizes: ["S", "M"],
  },
  {
    id: 8,
    title: "Urban Jacket",
    brand: "Sogar's Brand",
    price: 79,
    image: IMAGES.prod8,
    category: "men",
    type: "jackets",
    rating: 4.5,
    colors: ["beige"],
    sizes: ["M", "L", "XL"],
  },
  {
    id: 9,
    title: "Plain White T-Shirt",
    brand: "Jhanvi's Brand",
    price: 123,
    image: IMAGES.prod9,
    category: "men",
    type: "tshirts",
    rating: 4,
    colors: ["white"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 10,
    title: "Checks Shirt",
    brand: "HM's Brand",
    price: 123,
    image: IMAGES.prod10,
    category: "men",
    type: "shirts",
    rating: 4.5,
    colors: ["red"],
    sizes: ["M", "L"],
  },
  {
    id: 11,
    title: "Black Top",
    brand: "Nike's Brand",
    price: 123,
    image: IMAGES.prod11,
    category: "women",
    type: "tops",
    rating: 5,
    colors: ["black"],
    sizes: ["S", "M"],
  },
  {
    id: 12,
    title: "Denim Blue Shirt",
    brand: "MOMO's Brand",
    price: 38,
    image: IMAGES.prod12,
    category: "men",
    type: "shirts",
    rating: 4,
    colors: ["blue"],
    sizes: ["M", "L", "XL"],
  },
  {
    id: 13,
    title: "Floral Summer Dress",
    brand: "Femme's Brand",
    price: 89,
    image: IMAGES.prod13,
    category: "women",
    type: "dresses",
    rating: 5,
    colors: ["pink"],
    sizes: ["XS", "S", "M"],
  },
  {
    id: 14,
    title: "Beige Trench Coat",
    brand: "Lux's Brand",
    price: 199,
    image: IMAGES.prod14,
    category: "women",
    type: "coats",
    rating: 4.5,
    colors: ["beige"],
    sizes: ["S", "M", "L"],
  },
  {
    id: 15,
    title: "Knit Joggers",
    brand: "Comfy's Brand",
    price: 55,
    image: IMAGES.prod15,
    category: "men",
    type: "joggers",
    rating: 4,
    colors: ["gray"],
    sizes: ["M", "L", "XL"],
  },
  {
    id: 16,
    title: "Yellow Sweatshirt",
    brand: "Sun's Brand",
    price: 77,
    image: IMAGES.prod16,
    category: "women",
    type: "hoodies",
    rating: 4.5,
    colors: ["yellow"],
    sizes: ["S", "M", "L"],
  },
];

export const MOCK_CATEGORIES = {
  men: [
    { id: "m1", title: "Shirts", image: IMAGES.catMenShirts },
    { id: "m2", title: "Printed T-Shirts", image: IMAGES.catMenPrinted },
    { id: "m3", title: "Plain T-Shirt", image: IMAGES.catMenPlain },
    { id: "m4", title: "Polo T-Shirt", image: IMAGES.catMenPolo },
    { id: "m5", title: "Hoodies", image: IMAGES.catMenHoodies },
    { id: "m6", title: "Jeans", image: IMAGES.catMenJeans },
    { id: "m7", title: "Activewear", image: IMAGES.catMenActive },
    { id: "m8", title: "Boxers", image: IMAGES.catMenBoxers },
  ],
  women: [
    { id: "w1", title: "Hoodies", image: IMAGES.catWomenHoodies },
    { id: "w2", title: "Coats & Parkas", image: IMAGES.catWomenCoats },
    { id: "w3", title: "Tees & T-Shirt", image: IMAGES.catWomenTees },
    { id: "w4", title: "Dresses", image: IMAGES.catWomenDresses },
  ],
};

export const MOCK_NEW_ARRIVAL = [
  { id: "na1", title: "Knitted Joggers", image: IMAGES.naJoggers },
  { id: "na2", title: "Full Sleeve", image: IMAGES.naSleeve },
  { id: "na3", title: "Active T-Shirts", image: IMAGES.naActive },
  { id: "na4", title: "Urban Shirts", image: IMAGES.naUrban },
];

export const MOCK_BIG_SAVING = [
  {
    id: "bs1",
    title: "Hawaiian Shirts",
    subtitle: "Dress up in summer vibe",
    discount: "UPTO 50% OFF",
    image: IMAGES.bsHawaiian,
    bg: "#5DADE2",
    color: "white",
  },
  {
    id: "bs2",
    title: "Printed T-Shirt",
    subtitle: "New Designs Every Week",
    discount: "UPTO 40% OFF",
    image: IMAGES.bsPrinted,
    bg: "#F5B7B1",
    color: "white",
  },
  {
    id: "bs3",
    title: "Cargo Joggers",
    subtitle: "Move with style & comfort",
    discount: "UPTO 50% OFF",
    image: IMAGES.bsCargo,
    bg: "#D5DBDB",
    color: "black",
  },
  {
    id: "bs4",
    title: "Urban Shirts",
    subtitle: "Live In Comfort",
    discount: "FLAT 60% OFF",
    image: IMAGES.bsUrban,
    bg: "#F0E5D8",
    color: "black",
  },
  {
    id: "bs5",
    title: "Oversized T-Shirts",
    subtitle: "Street Style Icon",
    discount: "FLAT 60% OFF",
    image: IMAGES.bsOversized,
    bg: "#AED6F1",
    color: "black",
  },
];

export const MOCK_BRANDS = ["Nike", "H&M", "Levi's", "U.S. Polo", "Puma"];

export const MOCK_FEEDBACK = [
  {
    id: 1,
    name: "Floyd Miles",
    avatar: IMAGES.avatarFloyd,
    rating: 4,
    text: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
  },
  {
    id: 2,
    name: "Ronald Richards",
    avatar: IMAGES.avatarRonald,
    rating: 4,
    text: "Ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
  },
  {
    id: 3,
    name: "Savannah Nguyen",
    avatar: IMAGES.avatarSavannah,
    rating: 4,
    text: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
  },
];

export const MOCK_HERO_SLIDES = [
  {
    id: 1,
    eyebrow: "T-Shirt / Tops",
    title: "Summer\nValue Pack",
    subtitle: "cool / colorful / comfy",
    image: IMAGES.heroSummer,
    bg: "#1EA9DD",
    textColor: "white",
  },
  {
    id: 2,
    eyebrow: "New Collection",
    title: "Spring\nVibes",
    subtitle: "fresh / modern / light",
    image: IMAGES.heroSpring,
    bg: "#F8B8C8",
    textColor: "white",
  },
  {
    id: 3,
    eyebrow: "Winter Deals",
    title: "Cozy\nSeason",
    subtitle: "warm / soft / stylish",
    image: IMAGES.heroCozy,
    bg: "#2C4B44",
    textColor: "white",
  },
];
